root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
pre_cmd = ["task templ-fmt"]
cmd = "go build -o ./tmp/main ./cmd/server/"
exclude_dir = ["assets", "~builds", "tmp", "vendor"]
exclude_file = []
exclude_regex = [".*_templ.txt", ".*_string.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ", "tpl", "tmpl", "html", "sql", "yaml", "css"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true

[proxy]
enabled = true
proxy_port = 54321
app_port = 8080
