root = "."
tmp_dir = "~builds"

[build]
bin = "./~builds/air_server"
cmd = "task air-rebuild-cmd"
delay = 1000
exclude_dir = ["assets", "~builds", "vendor"]
exclude_file = []
exclude_regex = [".*_templ.txt", ".*_string.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "css"]
kill_delay = "2s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
