services:

  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    volumes:
      - ./configs/grafana-provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3010:3000"
    depends_on:
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    networks:
      - monitoring

networks:
  monitoring:


volumes:
  prometheus_data: {}
  grafana_data: {}
