version: "3"

env:
  ENV: ./

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  dev:
    deps: [tailwind-cli-dev, templ, air]

  templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8080"  --proxybind="0.0.0.0" --proxyport="54321" --open-browser=false

  air:
    cmds:
      - air
      
  air-rebuild-cmd:
    cmds:
      - sqlc generate -f ./build/sqlc.yaml
      - go build -o ./tmp/main ./cmd/server/
      - templ generate --notify-proxy --proxybind='localhost' --proxyport='54321'

  tailwind-cli-dev:
    cmds:
      - ./~tailwindcss -i build/global.css -o assets/css/tailwind.css --watch
    deps: [tailwind-cli-download]

  tailwind-cli-prod:
    cmds:
      - ./~tailwindcss -i build/global.css -o assets/css/tailwind.css --minify
    deps: [tailwind-cli-download]

  tailwind-cli-download:
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.12/tailwindcss-linux-x64
      - chmod +x tailwindcss-linux-x64
      - mv tailwindcss-linux-x64 ~tailwindcss
    status:
      - ./~tailwindcss

  update-apps:
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest

  goose-up:
    cmds:
      - goose -dir ./migrations up-by-one

  goose-down:
    cmds:
      - goose -dir ./migrations down

  goose-create:
    cmds:
      - goose -dir ./migrations create {{.CLI_ARGS}} sql