version: "3"

vars:
  templ:  github.com/a-h/templ/cmd/templ@latest
  sqlc:   github.com/sqlc-dev/sqlc/cmd/sqlc@latest
  air:    github.com/air-verse/air@latest

env:
  ENV: ./

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  goose:    ./Taskfile.Goose.yml
  tailwind: ./Taskfile.Tailwind.yml
  langs:    ./Taskfile.i18n.yml

tasks:
  default:
    cmds:
      - task --list-all

  dev:
    deps: [tailwind:dev, templ, air]

  templ-fmt: go run {{.templ}} fmt .

  templ: go run {{.templ}} generate --watch --open-browser=false -v
  air: go run {{.air}}
    
  update-refactoring-tools:
      - go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
      - go install github.com/davidrjenni/reftools/cmd/fillswitch@latest
      - go install github.com/davidrjenni/reftools/cmd/fixplurals@latest

  regen:
      - go generate ./...
      - task sqlc-gen-dev
      - task langs:refresh

  pre-build-prod:
      - go generate ./...
      - go run {{.templ}} generate 
      - task sqlc-gen-prod

  sqlc-gen-prod: go run {{.sqlc}} generate -f ./build/sqlc_prod.yaml
  sqlc-gen-dev:
      - set -a
      - source .env 
      - set +a 
      - go run {{.sqlc}} generate -f ./build/sqlc_dev.yaml

  build-current: go build -trimpath -tags embed -o ./~builds/server ./cmd/server/.
  build-freebsd-amd64: env GOOS=freebsd GOARCH=amd64 go build -trimpath -tags embed -o ./~builds/freebsd/amd64/server ./cmd/server/.