version: "3"

env:
  ENV: ./

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  goose: ./Taskfile.Goose.yml
  tailwind: ./Taskfile.Tailwind.yml
  langs: ./Taskfile.i18n.yml

tasks:
  dev:
    deps: [tailwind:dev, templ, air]

  templ:
    cmds:
      - templ generate --watch --proxy="http://localhost:8080"  --proxybind="0.0.0.0" --proxyport="54321" --open-browser=false

  air:
    cmds:
      - air
      
  air-rebuild-cmd:
    cmds:
      - sqlc generate -f ./build/sqlc.yaml
      - task langs:refresh
      - templ generate --notify-proxy --proxybind='localhost' --proxyport='54321'
      - go build -o ./tmp/main ./cmd/server/

  update-apps:
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install -v github.com/nicksnyder/go-i18n/v2/goi18n@latest