version: "3"

vars:
  templ:  github.com/a-h/templ/cmd/templ@latest
  sqlc:   github.com/sqlc-dev/sqlc/cmd/sqlc@latest
  air:    github.com/air-verse/air@latest

env:
  ENV: ./

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

includes:
  goose: ./Taskfile.Goose.yml
  tailwind: ./Taskfile.Tailwind.yml
  langs: ./Taskfile.i18n.yml

tasks:
  dev:
    cmds:
      - air
    deps: [tailwind:dev, templ]

  templ:
<<<<<<< HEAD
    cmds:
<<<<<<< HEAD
<<<<<<< HEAD
      - templ generate --watch
=======
      - templ generate --watch --proxy="http://localhost:8080"  --proxybind="0.0.0.0" --proxyport="54321" --open-browser=false
=======
      - {{.templ}} generate --watch --open-browser=false -v
>>>>>>> 41f451c (clean taskfiles from install, fixed air long rebuild)
=======
    cmds: 
      - go run {{.templ}} generate --watch --open-browser=false -v
>>>>>>> f6eaba0 (++clean taskfiles from install, fixed air long rebuild)

  air:
    cmds:
      - go run {{.air}}
      
  regen:
    cmds:
      - go generate ./...
      - task sqlc-gen
      - task langs:refresh
<<<<<<< HEAD
<<<<<<< HEAD
      - templ generate --notify-proxy --proxybind='localhost' --proxyport='54321'
      - go build -o ./~builds/air_server ./cmd/server/
>>>>>>> 332ecda (Revert "replaced templ proxy with air proxy")

  update-apps:
    cmds:
      - task update-build-apps
      - go install github.com/air-verse/air@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install github.com/dmji/go-i18n/goi18n@1f1416ba51b312f0b357a4119963aa48e8042c83
=======
>>>>>>> 41f451c (clean taskfiles from install, fixed air long rebuild)

  update-build-apps:
    cmds:
      - go run github.com/dmji/go-stringer@latest
=======
>>>>>>> f6eaba0 (++clean taskfiles from install, fixed air long rebuild)
    
  update-refactoring-tools:
    cmds:
      - go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
      - go install github.com/davidrjenni/reftools/cmd/fillswitch@latest
      - go install github.com/davidrjenni/reftools/cmd/fixplurals@latest

<<<<<<< HEAD
  pre-build-dev:
    cmds:
      - go generate ./...
    deps: [langs:refresh, sqlc-gen-dev]

  pre-build-prod:
    cmds:
      - go generate ./...
<<<<<<< HEAD
      - templ generate 
    deps: [langs:refresh, sqlc-gen-prod]
=======
      - {{.templ}} generate 
=======
  pre-build-prod:
    cmds:
      - go generate ./...
      - go run {{.templ}} generate 
>>>>>>> f6eaba0 (++clean taskfiles from install, fixed air long rebuild)
      - task sqlc-gen-prod
>>>>>>> 41f451c (clean taskfiles from install, fixed air long rebuild)

  sqlc-gen-dev:
    cmds:
      - set -a
      - source .env 
      - set +a 
      - go run {{.sqlc}} generate -f ./build/sqlc.yaml

  sqlc-gen-prod:
    cmds:
<<<<<<< HEAD
<<<<<<< HEAD
      - sqlc generate -f ./build/sqlc_prod.yaml
=======
      - {{.sqlc}} generate -f ./build/sqlc_prod.yaml
=======
      - go run {{.sqlc}} generate -f ./build/sqlc_prod.yaml
>>>>>>> f6eaba0 (++clean taskfiles from install, fixed air long rebuild)

  build-current:
    cmds:
      - go build -trimpath -tags embed -o ./~builds/server ./cmd/server/.
      
  build-freebsd-amd64:
    cmds:
      - env GOOS=freebsd GOARCH=amd64 go build -trimpath -tags embed -o ./~builds/freebsd/amd64/server ./cmd/server/.
>>>>>>> 41f451c (clean taskfiles from install, fixed air long rebuild)
