// Code generated by "stringer -type=UpdateableField -trimprefix=UpdateableField -output enum_updateable_field_string.go -nametransform=snake_case_lower -fromstringgenfn -outputtransform=snake_case_lower -extraconstsnameprefix=_ -extraconstsnamesuffix=_i18n_ID -extraconstsvaluetransform=pascal_case -extraconstsvaluesuffix=Presentation"; DO NOT EDIT.

package model

import "strconv"
import "errors"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateableFieldTitle-0]
	_ = x[UpdateableFieldReleaseStatus-1]
	_ = x[UpdateableFieldLastCheckedDate-2]
	_ = x[UpdateableFieldCreatedDate-3]
	_ = x[UpdateableFieldUpdatedDate-4]
	_ = x[UpdateableFieldTorrentFilesSize-5]
	_ = x[UpdateableFieldNotes-6]
	_ = x[UpdateableFieldIdentifier-7]
}

const _UpdateableField_name = "titlerelease_statuslast_checked_datecreated_dateupdated_datetorrent_files_sizenotesidentifier"

var _UpdateableField_index = [...]uint8{0, 5, 19, 36, 48, 60, 78, 83, 93}

func (i UpdateableField) String() string {
	if i < 0 || i >= UpdateableField(len(_UpdateableField_index)-1) {
		return "UpdateableField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateableField_name[_UpdateableField_index[i]:_UpdateableField_index[i+1]]
}
func UpdateableFieldFromString(s string) (UpdateableField, error) {
	for i := 0; i < 8; i++ {
		if e := UpdateableField(i + 0); s == e.String() {
			return e, nil
		}
	}
	return UpdateableField(0), errors.New("cannot deternime UpdateableField from string")
}

const (
	_UpdateableFieldTitle_i18n_ID            = "ModelUpdateableFieldTitlePresentation"
	_UpdateableFieldReleaseStatus_i18n_ID    = "ModelUpdateableFieldReleaseStatusPresentation"
	_UpdateableFieldLastCheckedDate_i18n_ID  = "ModelUpdateableFieldLastCheckedDatePresentation"
	_UpdateableFieldCreatedDate_i18n_ID      = "ModelUpdateableFieldCreatedDatePresentation"
	_UpdateableFieldUpdatedDate_i18n_ID      = "ModelUpdateableFieldUpdatedDatePresentation"
	_UpdateableFieldTorrentFilesSize_i18n_ID = "ModelUpdateableFieldTorrentFilesSizePresentation"
	_UpdateableFieldNotes_i18n_ID            = "ModelUpdateableFieldNotesPresentation"
	_UpdateableFieldIdentifier_i18n_ID       = "ModelUpdateableFieldIdentifierPresentation"
)
