// Code generated by "stringer -type=ReleaseStatus -trimprefix=ReleaseStatus -output enum_release_status_string.go -nametransform=snake_case_lower -fromstringgenfn -outputtransform=snake_case_lower -extraconstsnameprefix=_ -extraconstsnamesuffix=_i18n_ID -extraconstsvaluetransform=pascal_case -extraconstsvaluesuffix=Presentation"; DO NOT EDIT.

package model

import "strconv"
import "errors"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReleaseStatusOnAir-0]
	_ = x[ReleaseStatusIncompleted-1]
	_ = x[ReleaseStatusCompleted-2]
}

const _ReleaseStatus_name = "on_airincompletedcompleted"

var _ReleaseStatus_index = [...]uint8{0, 6, 17, 26}

func (i ReleaseStatus) String() string {
	if i < 0 || i >= ReleaseStatus(len(_ReleaseStatus_index)-1) {
		return "ReleaseStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReleaseStatus_name[_ReleaseStatus_index[i]:_ReleaseStatus_index[i+1]]
}
func ReleaseStatusFromString(s string) (ReleaseStatus, error) {
	for i := 0; i < 3; i++ {
		if e := ReleaseStatus(i + 0); s == e.String() {
			return e, nil
		}
	}
	return ReleaseStatus(0), errors.New("cannot deternime ReleaseStatus from string")
}

const (
	_ReleaseStatusOnAir_i18n_ID       = "ModelReleaseStatusOnAirPresentation"
	_ReleaseStatusIncompleted_i18n_ID = "ModelReleaseStatusIncompletedPresentation"
	_ReleaseStatusCompleted_i18n_ID   = "ModelReleaseStatusCompletedPresentation"
)
