// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func styles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n        body {\n            font-family: Arial, sans-serif;\n            margin: 0;\n            padding: 0;\n            background-color: #f0f0f0;\n        }\n        .card-grid {\n            display: grid;\n            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n            gap: 1rem;\n            padding: 1rem;\n        }\n        .card {\n            display: flex;\n            flex-direction: column;\n\n            border: 1px solid #ddd;\n            border-radius: 8px;\n            overflow: hidden;\n            background-color: white;\n            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n        }\n        .card-content {\n            padding: 1rem;\n            height: 30%;\n        }\n        .card-description {\n            padding: 1rem;\n        }\n        .card img {\n            width: 100%;\n            height: 250px;\n            object-fit: scale-down;\n        }\n        .card-buttons {\n            align-items: center;\n            height: 50px;\n\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            padding: 0.5rem;\n            gap: 0.25rem;\n        }\n        .card-buttons a,\n        .card-buttons button {\n            padding: 0.25rem 0.5rem;\n            background-color: #f0f0f0;\n            border: 1px solid #ddd;\n            border-radius: 4px;\n            cursor: pointer;\n            transition: background-color 0.3s;\n        }\n        .card-buttons a  {\n            font: bold 11px Arial;\n            text-decoration: none;\n            color: #333333;\n        }\n        .card-buttons a:hover,\n        .card-buttons button:hover {\n            background-color: #22e0e0;\n        }\n        #loading, #end-message {\n            text-align: center;\n            padding: 1rem;\n            font-style: italic;\n            color: #666;\n        }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
